# ------------------
# Color theme - Dark
# ------------------

[".config/bat/themes/rose-pine.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/tm-theme/main/dist/themes/rose-pine.tmTheme"
refreshPeriod = "168h"

[".config/btop/themes/rose-pine.theme"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/btop/main/rose-pine.theme"
refreshPeriod = "168h"

[".config/kitty/themes/rose-pine.conf"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/kitty/main/dist/rose-pine.conf"
refreshPeriod = "168h"

# -------------------
# Color Theme - Light
# -------------------

[".config/bat/themes/rose-pine-dawn.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/tm-theme/main/dist/themes/rose-pine-dawn.tmTheme"
refreshPeriod = "168h"

[".config/btop/themes/rose-pine-dawn.theme"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/btop/main/rose-pine-dawn.theme"
refreshPeriod = "168h"

# -----------
# ZSH plugins
# -----------

[".config/zsh/plugins/history-substring-search/external"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-history-substring-search.git"
refreshPeriod = "168h"

[".config/zsh/plugins/autosuggestions/external"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".config/zsh/plugins/lscolors/external/lscolors.sh"]
type = "file"
url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.sh"
refreshPeriod = "168h"
