[tools]
bun = "latest"
node = "lts"
pnpm = "latest"
python = "3.12"
usage = "latest"
uv = "latest"
zig = "latest"

# lsp
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:graphql-language-service-cli" = "latest"
"ubi:kristoff-it/superhtml" = "latest"
"ubi:luals/lua-language-server" = "latest"
"ubi:artempyanykh/marksman" = "latest"
"npm:pyright" = "latest"
"pipx:ruff-lsp" = "latest"
"ubi:tamasfe/taplo" = "latest"
"npm:sql-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:typescript-language-server" = "latest"
"ubi:nvarner/typst-lsp" = "latest"
"npm:@vue/language-server" = "latest"
"npm:yaml-language-server" = "latest"
"ubi:zigtools/zls" = "latest"

[settings]
experimental = true
legacy_version_file = false
plugin_autoupdate_last_check_duration = "1 week"
trusted_config_paths = ["~/Projects", "~/Workspace"]
status = { show_env = true }
pipx_uvx = true
disable_hints = ["python_multi", "python_precompiled"]
