[tools]
bun = "latest"
node = "lts"
pnpm = "latest"
usage = "latest"
uv = "latest"
zig = "latest"

# lsp
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:pyright" = "latest"
"npm:sql-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:yaml-language-server" = "latest"

"aqua:LuaLS/lua-language-server" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:zigtools/zls" = "latest"
"aqua:tamasfe/taplo" = "latest"
"aqua:nvarner/typst-lsp" = "latest"
"ubi:kristoff-it/superhtml" = "latest"
"ubi:artempyanykh/marksman" = "latest"

[settings]
disable_hints = ["python_multi", "python_precompiled"]
experimental = true
idiomatic_version_file = false
trusted_config_paths = ["~/Projects", "~/Workspace"]

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[settings.status]
show_env = true
