[tools]
bun = "latest"
usage = "latest"
uv = "latest"
zig = "latest"
just = "latest"
prek = "latest"

# ----------
# formatters
# ----------
"npm:prettier" = "latest"

# ---
# lsp
# ---

# bash
"npm:bash-language-server" = "latest"
shellcheck = "latest"
shfmt = "latest"
# html, css, json
"npm:vscode-langservers-extracted" = "latest"
# docker
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
# go
# graphql
"npm:graphql-language-service-cli" = "latest"
# helm
"ubi:mrjosh/helm-ls" = "latest"
# lua
"lua-language-server" = "latest"
# markdown
"marksman" = "latest"
# python
"npm:basedpyright" = "latest"
"ruff" = "latest"
# sql
"npm:sql-language-server" = "latest"
# tailwindcss
"npm:@tailwindcss/language-server" = "latest"
# toml
"taplo" = "latest"
# typescript
"npm:typescript-language-server" = "latest"
# vue
"npm:@vue/language-server" = "latest"
# yaml
"npm:yaml-language-server" = "latest"
# zig
"zls" = "latest"

[settings]
disable_backends = [
  "asdf",
  "cargo",
  "dotnet",
  "gem",
  "github",
  "gitlab",
  "go",
  "http",
  "spm",
  "vfox",
]
disable_hints = ["python_multi", "python_precompiled"]
experimental = true
idiomatic_version_file_enable_tools = []
trusted_config_paths = ["~/Projects", "~/Workspace"]

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[settings.status]
show_env = true
