[tools]
bun = "latest"
node = "lts"
pnpm = "latest"
python = "3.12"
usage = "latest"
uv = "latest"
zig = "latest"

[settings]
experimental = true
legacy_version_file = false
plugin_autoupdate_last_check_duration = "1 week"
trusted_config_paths = ["~/Projects", "~/Workspace"]
status = { show_env = true }
